name: ekram_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.0
  firebase_storage: ^11.7.2
  image_picker: ^1.1.0
  image_card: ^0.0.4
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  get: ^4.6.6
  carousel_slider: ^4.2.1
  awesome_dialog: ^3.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0



#flutter_native_splash:
#android_12:
#   color: "#ffffff"
#   image: images/logo.png
#   android: true
#   ios: true
#   web: false
#   android_gravity: fill
#   ios_content_mode: scaleAspectFill
#   fullscreen: true
# android_12:
#     image: images/logo.png
#     icon_background_color: "#ffffff"
  




# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  
  assets:
    - images/
    - asset/icons/


  
  fonts:
    - family: ElMessiri
      fonts:
        - asset: asset/fonts/ElMessiri-Regular.ttf
        - asset: asset/fonts/ElMessiri-Bold.ttf
        - asset: asset/fonts/ElMessiri-SemiBold.ttf
    - family: Amiri
      fonts:
        - asset: asset/fonts/Amiri-Regular.ttf
        - asset: asset/fonts/Amiri-Bold.ttf
        - asset: asset/fonts/Amiri-BoldItalic.ttf
    - family: Open_Sans
      fonts:
        - asset: asset/fonts/OpenSans_Condensed-Bold.ttf
        - asset: asset/fonts/OpenSans_Condensed-Regular.ttf
        - asset: asset/fonts/OpenSans_Condensed-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Bold.ttf
        - asset: asset/fonts/Roboto-BoldItalic.ttf
        - asset: asset/fonts/Roboto-Regular.ttf


    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
