// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppTe5E7X-0q_-bZscMmrF2h4bh52uBwU',
    appId: '1:884494493591:web:7e4088b084199fcdf146d2',
    messagingSenderId: '884494493591',
    projectId: 'clinic-project-17f49',
    authDomain: 'clinic-project-17f49.firebaseapp.com',
    storageBucket: 'clinic-project-17f49.appspot.com',
    measurementId: 'G-MK1EJSQ8D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZBVcar1eT7HiEk5Ie2LQ2sAqs83mfwDc',
    appId: '1:884494493591:android:76dda9579647990af146d2',
    messagingSenderId: '884494493591',
    projectId: 'clinic-project-17f49',
    storageBucket: 'clinic-project-17f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BEWq1viTkWMANF6LcG8XYiBhmpHrhO4',
    appId: '1:884494493591:ios:6d309ad0b2178753f146d2',
    messagingSenderId: '884494493591',
    projectId: 'clinic-project-17f49',
    storageBucket: 'clinic-project-17f49.appspot.com',
    iosBundleId: 'com.example.ekramProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9BEWq1viTkWMANF6LcG8XYiBhmpHrhO4',
    appId: '1:884494493591:ios:a9581e76885b24eff146d2',
    messagingSenderId: '884494493591',
    projectId: 'clinic-project-17f49',
    storageBucket: 'clinic-project-17f49.appspot.com',
    iosBundleId: 'com.example.ekramProject.RunnerTests',
  );
}
